export const MSG_DETAIL_PAGE_INIT_STATE = "MSG_DETAIL_PAGE_INIT_STATE";
export const MSG_DETAIL_PAGE_ADJUST_LOADING_HEIGHT = "MSG_DETAIL_PAGE_ADJUST_LOADING_HEIGHT";
export const MSG_DETAIL_PAGE_FETCH_DETAIL_SUCCESS = "MSG_DETAIL_PAGE_FETCH_DETAIL_SUCCESS";
export const MSG_DETAIL_PAGE_FETCH_DETAIL_FAIL = "MSG_DETAIL_PAGE_FETCH_DETAIL_FAIL";
export const MSG_DETAIL_PAGE_ADJUST_CONTENT_HEIGHT = "MSG_DETAIL_PAGE_ADJUST_CONTENT_HEIGHT";
export const MSG_DETAIL_PAGE_RESET_LOADING_STATUS = "MSG_DETAIL_PAGE_RESET_LOADING_STATUS";

export const MSG_LIST_PAGE_TRY_RESTORE_COMPONENT = "MSG_LIST_PAGE_TRY_RESTORE_COMPONENT";
export const MSG_LIST_PAGE_FETCH_ITEMS_SUCCESS = "MSG_LIST_PAGE_FETCH_ITEMS_SUCCESS";
export const MSG_LIST_PAGE_FETCH_ITEMS_FAIL = "MSG_LIST_PAGE_FETCH_ITEMS_FAIL";
export const MSG_LIST_PAGE_UPDATE_PULLDOWN_STATUS = "MSG_LIST_PAGE_UPDATE_PULLDOWN_STATUS";
export const MSG_LIST_PAGE_UPDATE_PULLUP_STATUS = "MSG_LIST_PAGE_UPDATE_PULLUP_STATUS";
export const MSG_LIST_PAGE_BACKUP_ISCROLL_Y = "MSG_LIST_PAGE_BACKUP_ISCROLL_Y";
export const MSG_LIST_PAGE_UPDATE_LOADING_STATUS = "MSG_LIST_PAGE_UPDATE_LOADING_STATUS";

export const SLIDER_INIT_STATE = "SLIDER_INIT_STATE";
export const SLIDER_SLIDE = "SLIDER_SLIDE";