export const MSG_DETAIL_PAGE_INIT_STATE = "MSG_DETAIL_PAGE_INIT_STATE";
export const MSG_DETAIL_PAGE_ADJUST_LOADING_HEIGHT = "MSG_DETAIL_PAGE_ADJUST_LOADING_HEIGHT";
export const MSG_DETAIL_PAGE_FETCH_DETAIL = "MSG_DETAIL_PAGE_ADJUST_FETCH_DETAIL";
export const MSG_DETAIL_PAGE_ADJUST_CONTENT_HEIGHT = "MSG_DETAIL_PAGE_ADJUST_CONTENT_HEIGHT";

export const MSG_LIST_PAGE_TRY_RESTORE_COMPONENT = "MSG_LIST_PAGE_TRY_RESTORE_COMPONENT";
export const MSG_LIST_PAGE_FETCH_ITEMS = "MSG_LIST_PAGE_FETCH_ITEMS";
export const MSG_LIST_PAGE_UPDATE_PULLDOWN_STATUS = "MSG_LIST_PAGE_UPDATE_PULLDOWN_STATUS";
export const MSG_LIST_PAGE_UPDATE_PULLUP_STATUS = "MSG_LIST_PAGE_UPDATE_PULLUP_STATUS";
export const MSG_LIST_PAGE_BACKUP_ISCROLL_Y = "MSG_LIST_PAGE_BACKUP_ISCROLL_Y";

export const SLIDER_INIT_STATE = "SLIDER_INIT_STATE";
export const SLIDER_SLIDE = "SLIDER_SLIDE";